### ISSUE TITLE
Problem in inference

### ISSUE THREAD

**Issue by playdasegunda** [etzinis/sudo_rm_rf#10]
Would it be possible to add simpler information on how to use sudo_rm_rf ? I tried to use it but without success, changing the directories of "sudormrf_how_to_use.ipynb" but it still didn't work,

If it's possible to create a google colab or help how to use it, it would be interesting for the community, thanks in advance.

**Comment by etzinis** [comment]
Hey, could you please explain what is the problem with using that notebook?

**Comment by playdasegunda** [comment]
So this is the colab I created based on your released notebook, however in (cell 3) I find the following error,

if you want to see what's wrong, or if you want to edit it's up to you,

https://colab.research.google.com/drive/1vmrHKuL20JMAEBqGvDnq6nNsn6rmiQ9w

Thank you very much.

**Comment by etzinis** [comment]
Your problem is installing torch, just simply install the packages needed without the requirements file. Should be fairly straightforward
