### ISSUE TITLE
Activation function in UBlock

### ISSUE THREAD

**Issue by hsiaohan0827** [etzinis/sudo_rm_rf#14]
Hi, I noticed that each downsampling stage resembles a DWConv+LN+PReLU, as shown in algorithm 1 in the paper.
But it seems like the code of this downsampling process contains only DWConv+LN in [Line 147](https://github.com/etzinis/sudo_rm_rf/blob/a265b4a37063ccb613117b26dc137f52741abf6e/sudo_rm_rf/dnn/models/sudormrf.py#L147).
Is PReLU applied in the UBlock? Thanks.

**Comment by etzinis** [comment]
You are right, this was probably a typo in the paper, I do not think that makes a difference besides increasing the parameters a bit.
