### ISSUE TITLE
Saving the model

### ISSUE THREAD

**Issue by under-funk** [etzinis/sudo_rm_rf#16]
Hi, I would like to save the model with the best results for my experiments but I did not get a clear understanding from improved_cmd_args_parser_v2.py, would option -elp or -clp would save my model? say if I am running my model for 100 epoch if I put -clp $path$ --save_checkpoint_every 100, would it save my model at the end of experiment. Or there is another way to save the model in pt or pth? Also the Comet_ml support is a really cool feature but I was wondering if the model is saved there and I can extract it or unless I put the correct parameters my experiment would not be saved anywhere locally

Again I use the command 

python run_improved_sudormrf.py --train WHAM --val WHAM --test WHAM --train_val WHAM --separation_task sep_clean --n_train 20000 --n_test 3000 --n_val 3000 --n_train_val 3000 --out_channels 256 --num_blocks 16 -cad 0 1 --n_jobs 8 --divide_lr_by 3. --upsampling_depth 5 --patience 49 -fs 8000 -tags sudo_rm_rf_16 --project_name sudormrf_wham --zero_pad --clip_grad_norm 5.0 --model_type relu --n_epochs 100 -bs 7

And there is no output file. How can I get a pt file for my experiement?

Thank you very much and great work!

**Comment by etzinis** [comment]
The elp sets your local path to save the model, so it will not necessarily upload a model to the cometml platform. You can change the code if you want to save more checkpoints or smth like that: https://github.com/etzinis/sudo_rm_rf/blob/master/sudo_rm_rf/dnn/experiments/run_improved_sudormrf.py#L221

**Comment by under-funk** [comment]
Thanks. If I understand correctly if it is uploaded to cometml there is no way to download it from there and it is a must to use the -elp option. I will adjust my parameters and code accordingly.
