### ISSUE TITLE
Didn't get the result I wanted.

### ISSUE THREAD

**Issue by afterimagex** [etzinis/sudo_rm_rf#17]
I selected several custom noise files and input them into the network. Then I found that there was no noise reduction effect. I followed the sudormrf_how_to_use.ipynb file. I was curious whether the provided pre training model was only valid in the whamr data set.

**Comment by etzinis** [comment]
No it is not - it should be able to provide noise reduction with ohter files. Try to make sure you sample at 8kHz, normalize your input.
