### ISSUE TITLE
Specific instructions please..

### ISSUE THREAD

**Issue by joeoct93** [etzinis/sudo_rm_rf#19]
I've been trying to run this, but I'm not sure about the specifics.
I tried running the command:
python run_sudormrf_gc_v2.py --train LIBRI2MIX --val LIBRI2MIX --test LIBRI2MIX --train_val LIBRI2MIX \
--separation_task sep_clean --n_train 50800 --n_test 3000 --n_val 3000 --n_train_val 3000 \
--out_channels 512 --in_channels 256 --enc_kernel_size 21 --num_blocks 16 -cad 0 -bs 3 --divide_lr_by 3. --upsampling_depth 5 \
--patience 30 -fs 8000 -tags best_separation_model --project_name sudormrf_libri2mix --zero_pad --clip_grad_norm 5.0

I know the path for Libri2mix is in the command, but it doesn't work when I replace it with the Libri2mix I generated. Is it supposed the path to be to the mix folder? The csv? the sources? Without more specific instructions, I can't even try this out. Please give more specific instructions on these.

**Comment by etzinis** [comment]
I have absolutely no idea what your error is, how you generated the libri2mix if you have set the path for librimix in the config file. The instructions are not perfect but you can first try to set the right path in the config file: 
mine was: LIBRI2MIX_ROOT_PATH = '/mnt/data/libri_mix/Libri2Mix'
➜  src cd /mnt/data/libri_mix/Libri2Mix 
➜  Libri2Mix ls
wav16k  wav8k
