### ISSUE TITLE
Obtained results of SI-SNRi=18.9?

### ISSUE THREAD

**Issue by JusperLee** [etzinis/sudo_rm_rf#2]
What kind of script can be used to make SI-SNRi reach 18.9?

**Comment by etzinis** [comment]
python run_improved_sudormrf.py --train WHAM --val WHAM --test WHAM --train_val WHAM --separation_task sep_clean --n_train 20000 --n_test 3000 --n_val 3000 --n_train_val 3000 --out_channels 512 --num_blocks 34 -cad 0 1 -bs 4 --divide_lr_by 3. --upsampling_depth 5 --patience 49 -fs 8000 -tags sudo_rm_rf_34 --project_name sudormrf_wham --zero_pad --clip_grad_norm 5.0 --model_type relu

**Comment by JusperLee** [comment]
thanks a lot

**Comment by JusperLee** [comment]
I can't get the result of 18.9 with this parameter. I would like to ask if you have a log file for reference. @etzinis

**Comment by etzinis** [comment]
What is the result you are getting ? Are you using my code 100%?

**Comment by etzinis** [comment]
I double checked the result with my implementation here and an asteroid implementation as well

**Comment by JusperLee** [comment]
val_sisnri: 18.205505715329497. I used your code 100%.

**Comment by etzinis** [comment]
Also you have to let ot run for 200 epochs

**Comment by JusperLee** [comment]
but my code batch-size is not 4, I set it 16.

**Comment by etzinis** [comment]
So it's not the same...

**Comment by JusperLee** [comment]
ok, i will set batch size to 4 and test again.

**Comment by etzinis** [comment]
this is validation on test: 
![image](https://user-images.githubusercontent.com/22867082/89865369-311e1b00-db73-11ea-8ed8-4bbbd9e8ef39.png)

**Comment by etzinis** [comment]
I used patience = 30 here but this will not make a difference

**Comment by JusperLee** [comment]
I will try again to see if I can achieve this result.

**Comment by etzinis** [comment]
Btw how did you manage to fit a batch size of 16 in 2 GPUs or did you use more?

**Comment by JusperLee** [comment]
with 8 gpus, each gpu is  a batch size of 2.

**Comment by etzinis** [comment]
Wow glad that you have the resources.

**Comment by etzinis** [comment]
Also make sure you have the latest version of the code: git pull

**Comment by JusperLee** [comment]
![image](https://user-images.githubusercontent.com/33806018/89867559-ed172e80-dbe3-11ea-9767-e1630be9b545.png)
Is this result normal?

**Comment by etzinis** [comment]
yes totally normal. You have not even reduced the learnign rate for a second time and you are already at 18.2 probably you will score better than the paper :P

**Comment by JusperLee** [comment]
That's great, thanks a lot.

**Comment by JusperLee** [comment]
Hello, I cannot achieve the results in the paper by any method (SI-SNRi=18.9). I want to know a more detailed trick. @etzinis 
![image](https://user-images.githubusercontent.com/33806018/93285090-a03bfe80-f806-11ea-9b55-39cc4c3a8850.png)

**Comment by etzinis** [comment]
How much are you getting?

**Comment by JusperLee** [comment]
SI-SNRi = 18.66

**Comment by etzinis** [comment]
First of all, if I remember corresctly you were running with different batch size or something on multiple GPUs so that's one difference.

Despite that, round(18.66, 1) = 18.7 => 18.9 - 18.7 = 0.2 dB (almost 1% relative difference) which is not statistically neither acoustically different by any means.

**Comment by etzinis** [comment]
There is no other trick besides running the code as specified in the paper.

**Comment by JusperLee** [comment]
Okay, then there is no problem.

**Comment by JusperLee** [comment]
Thank you very much for your answers
