### ISSUE TITLE
'SuDORMRF' object has no attribute 'n_least_samples_req' Error 

### ISSUE THREAD

**Issue by RyderZ-Neo** [etzinis/sudo_rm_rf#22]
Hello etzinis . I am a fan of your work. I ran into object has no attribute 'n_least_samples_req' error  when tried to run how_to_use notebook in master branch. 
` rec_sources_wavs = anechoic_separation_model(input_mix.unsqueeze(1))`. Everything works fine before that line of code. Please help me if you can .  @etzinis

**Comment by etzinis** [comment]
Hello there! Thanks for your kind words! I fixed the issue which was caused by a previous fix that broke things, please try to use the newer way (shown in README and in the notebook) on how to load the pre-trained models.

**Comment by RyderZ-Neo** [comment]
Thank you for your answer.
