### ISSUE TITLE
Provide a trained model and easy Anaconda integration

### ISSUE THREAD

**Issue by 0xBEEEF** [etzinis/sudo_rm_rf#4]
This project sounds quite interesting, and the impressions are quite good in themselves.

Unfortunately, I can't get a picture of the whole model without first doing some training. Could you please provide an already trained model? That would save time and money, and you could compare the models with your own examples.

Furthermore, it would be very practical if, similar to the above mentioned Demucs model, everything would be prepared for an Anaconda environment. This would again save time and would simplify the use of the models. The effort for this would not be so big, because only a yaml file would have to be provided.

**Comment by etzinis** [comment]
I will take a look at providing a few pretrained models, thanks for bringing that up.

I do not understand why you are refering to Demucs, yaml and Anaconda.
-Demucs is another paper.
-Yaml is a way to provide configurations, why does it matter to provide configurations if you have a pre-trained model that you can fetch?
-If you have torch installed with either pip or anaconda it is exactly the same. Btw I was trainign everything with anaconda myself.

**Comment by etzinis** [comment]
The pre-trained models are available online.
